[phases.setup]
nixPkgs = ["nodejs-18", "git", "gnused"]

[phases.install]
cmds = [
  "echo 'Iniciando reparaci√≥n de protocolos Git...'",
  "git config --global url.'https://github.com/'.insteadOf 'ssh://git@github.com/'",
  "find . -name 'yarn.lock' -exec sed -i 's/ssh:\\/\\/git@github.com\\//https:\\/\\/github.com\\//g' {} +",
  "find . -name 'package-lock.json' -exec sed -i 's/ssh:\\/\\/git@github.com\\//https:\\/\\/github.com\\//g' {} +",
  "yarn install --frozen-lockfile || npm install"
]

[start]
cmd = "npm start"
